<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <joint name="${prefix}base_joint" type="revolute">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${prefix}base_link" />
    <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Base Link -->
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}joint1" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link1"/>
      <!-- <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/> -->
      <origin xyz="0 0 ${height1 + axel_offset}" rpy="0 0 0"/>
      <!-- <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/> -->
    </joint>

    <!-- Middle Link -->
    <link name="${prefix}link1">
      <collision>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${height2}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${width*4.5} 0 ${height2/16 - axel_offset}" rpy="0 1.5708 0"/>
        <geometry>
          <box size="${width} ${width} ${height2}"/>
        </geometry>
        <material name="yellow"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
      </link>

      <joint name="${prefix}joint2" type="revolute">
        <parent link="${prefix}link1"/>
        <child link="${prefix}link2"/>
        <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
        <origin xyz="${height2/1.1} 0 ${height2/5.5 - axel_offset*2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.7"/>
      </joint>

      <!-- Top Link -->
      <link name="${prefix}link2">
        <collision>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0.5 0 ${height3/12 - axel_offset}" rpy="0 1.5708 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
        </link>

        <!-- <origin xyz="0 ${width} ${height3 - axel_offset*3}" -->

        <joint name="${prefix}joint3" type="prismatic">
          <parent link="${prefix}link2"/>
          <child link="${prefix}link3" />
          <limit effort="1000.0" lower="0" upper="3.14" velocity="0.5"/>
          <origin xyz="1.05 0 ${height3/10 - axel_offset}" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
          <dynamics damping="0.7"/>
        </joint>

        <link name="${prefix}link3">
        <collision>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
        </link>

        <joint name="${prefix}tool_joint" type="fixed">
          <origin xyz="0 0 1" rpy="0 0 0" />
          <parent link="${prefix}link3"/>
          <child link="${prefix}tool_link" />
        </joint>

        <!-- Tool Link -->
        <link name="${prefix}tool_link">
        </link>

  </xacro:macro>

</robot>
